version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Uncomment lines below only if not using Traefik
    # ports:
    #   - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.phasmo-journal.rule=Host(`phasmo.peace-dev.de`)
      - traefik.http.routers.phasmo-journal.entrypoints=websecure
      - traefik.http.routers.phasmo-journal.tls.certresolver=myresolver
      - traefik.http.services.phasmo-journal.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
